services:
  azure-ocr-api:
    build: ./azure-ocr-api
    container_name: azure-ocr-api
    env_file:
      - .env
    ports:
      - "8000:8000"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: "localhost"
      N8N_PORT: 5678
      N8N_PROTOCOL: "http"
    depends_on:
      - azure-ocr-api
